### ISSUE TITLE
Source?

### ISSUE THREAD

**Issue by n4ru** [The-Holy-Green-Padlock/super-motherload-map-editor#1]
Got excited when I saw this on Github, but there's no point in uploading it here if you're not going to provide the source. Would like to be able to use this app, thanks.

**Comment by The-Holy-Green-Padlock** [comment]
Thanks for getting in touch with me, I've uploaded the source now. Tell me what you think. Did you find this application from my Steam page?

**Comment by n4ru** [comment]
I found it via a comment on Steam, yes. Thank you very much for the source, will play around with it :)
